In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("MetroHealth83.csv")

In [5]:
df.shape

(83, 17)

In [6]:
df.isnull().sum()

Unnamed: 0           0
City                 0
NumMDs               0
RateMDs              0
NumHospitals         0
NumBeds              0
RateBeds             0
NumMedicare          0
PctChangeMedicare    0
MedicareRate         0
SSBNum               0
SSBRate              0
SSBChange            0
NumRetired           0
SSINum               0
SSIRate              0
SqrtMDs              0
dtype: int64

In [7]:
df.columns = [
    col.strip().lower().replace(" ", "_")
    for col in df.columns
]

# Drop unnecessary index column
if "unnamed:_0" in df.columns:
    df.drop(columns=["unnamed:_0"], inplace=True)

# Converting into numeric columns
numeric_columns = df.columns.drop("city")

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [18]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Handle missing values
df.fillna(df.median(numeric_only=True), inplace=True)

In [10]:
df.shape

(76, 16)

In [13]:
# New KPI Metrics

df["physician_hospital_ratio"] = df["nummds"] / df["numhospitals"]

df["medicare_growth_flag"] = np.where(
    df["pctchangemedicare"] > 5,
    "High Growth",
    "Normal Growth"
)

# Risk segmentation based on SSI rate
df["risk_category"] = pd.cut(
    df["ssirate"],
    bins=[0, 1500, 3000, np.inf],
    labels=["Low Risk", "Moderate Risk", "High Risk"]
)

In [14]:
# Check summary statistics
df.describe()

,nummds,ratemds,numhospitals,numbeds,ratebeds,nummedicare,pctchangemedicare,medicarerate,ssbnum,ssbrate,ssbchange,numretired,ssinum,ssirate,sqrtmds,physician_hospital_ratio
count,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000,76.000000
mean,1707.381579,278.868421,7.513158,1567.657895,307.855263,76195.223684,4.692105,14576.223684,87518.618421,16826.447368,4.672368,55313.552632,12559.000000,2351.592105,35.560003,197.175842
std,2051.478062,109.848301,6.553357,1545.896767,116.949642,76715.359088,3.208313,3608.395295,86591.454176,3968.886532,3.060091,56604.383799,14292.905067,880.624100,21.184269,103.579238
min,143.000000,104.000000,2.000000,141.000000,102.000000,10306.000000,-2.200000,8240.000000,11245.000000,10068.000000,-1.800000,6775.000000,1495.000000,820.000000,11.958300,48.000000
25%,338.250000,191.750000,3.000000,468.000000,216.250000,23088.250000,2.475000,11931.000000,26956.250000,13920.500000,2.400000,16565.000000,3537.000000,1677.250000,18.391400,111.950000
50%,843.500000,258.500000,5.000000,975.000000,286.500000,47986.000000,4.800000,13887.000000,55240.000000,16093.500000,4.800000,35072.500000,6955.000000,2310.000000,29.043100,183.055556
75%,2100.250000,342.750000,10.250000,2006.750000,369.750000,89247.750000,6.175000,16600.500000,103707.500000,19657.500000,6.025000,66598.750000,15213.500000,2776.000000,45.812900,270.216387
max,9410.000000,743.000000,32.000000,6177.000000,641.000000,330821.000000,12.800000,25474.000000,380405.000000,27674.000000,13.500000,254260.000000,72225.000000,4746.000000,97.005200,516.500000

In [15]:
# Data integrity checks
(df[numeric_columns] < 0).sum()

nummds               0
ratemds              0
numhospitals         0
numbeds              0
ratebeds             0
nummedicare          0
pctchangemedicare    3
medicarerate         0
ssbnum               0
ssbrate              0
ssbchange            4
numretired           0
ssinum               0
ssirate              0
sqrtmds              0
dtype: int64

In [19]:
# cleaned dataset download

df.to_csv("cleaned_healthcare_data.csv", index=False)

print("\nETL Process Completed Successfully.")
print("Cleaned dataset saved as cleaned_healthcare_data.csv")

ETL Process Completed Successfully.
Cleaned dataset saved as cleaned_healthcare_data.csv